"""Public library surface for SENTINEL_PY."""

from .coverage import (
    COVERAGE_JSON_FORMAT,
    COVERAGE_TOOL_VERSION,
    CallableMetric,
    CoverageFormatError,
    CoverageMetadata,
    CoverageReport,
    CrapGateResult,
    FileCoverage,
    MetricOrderingError,
    evaluate_crap_gate,
    load_coverage_json,
    measure_source,
    sort_callable_metrics,
)
from .crap import (
    AmbiguousCallableError,
    AnalysisError,
    CallableDefinition,
    CrapResult,
    IdentityDescriptor,
    SourceRange,
    UnsupportedCallableError,
    analyze_source,
    calculate_crap,
)
from .rendering import FractionRenderError, render_canonical_decimal
from .mutation import (
    MUTATION_STATES,
    MutantRecord,
    MutationGateError,
    MutationGateResult,
    evaluate_mutation_gate,
)
from .provenance import (
    CoverageReceipt,
    CoverageReceiptError,
    VerifiedCoverage,
    load_coverage_receipt,
    verify_coverage_receipt,
)

__all__ = [
    "AmbiguousCallableError",
    "AnalysisError",
    "CallableDefinition",
    "CallableMetric",
    "COVERAGE_JSON_FORMAT",
    "COVERAGE_TOOL_VERSION",
    "CoverageFormatError",
    "CoverageMetadata",
    "CoverageReport",
    "CoverageReceipt",
    "CoverageReceiptError",
    "CrapGateResult",
    "CrapResult",
    "FileCoverage",
    "FractionRenderError",
    "IdentityDescriptor",
    "MetricOrderingError",
    "MUTATION_STATES",
    "MutantRecord",
    "MutationGateError",
    "MutationGateResult",
    "SourceRange",
    "UnsupportedCallableError",
    "VerifiedCoverage",
    "analyze_source",
    "calculate_crap",
    "evaluate_crap_gate",
    "evaluate_mutation_gate",
    "load_coverage_json",
    "load_coverage_receipt",
    "measure_source",
    "render_canonical_decimal",
    "sort_callable_metrics",
    "verify_coverage_receipt",
]
